### ISSUE TITLE
Business entity table - List of businesses 

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#10]
Customer Name is FULL Title. how many times do I have to repeat that. 
Logo kay sath Customer name jo aa raha hai abhi, woh contact person ka aa raha hai, contact person is **NOT** the customer, yahan pe Full Title show karao. 

and please delete the full title column,,, just start mein customer name aa raha ho which is actually the full title.

**Comment by anjumanjum** [comment]
kindly Fix it

**Comment by NasirNiazkiyani** [comment]
it is fixed...
