### ISSUE TITLE
Business entity table - List of businesses - Filter Not working, Search not working

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#12]
Business entity kay table mein jo filter by business type lagaya hua hai woh chalta nahi hai. 
uss ki aur search box ki alignment bhi theek nahi hai. 

aur search bhi nahi chal raha. search karnay kay baad bhi jub table empty ho jata hai to wapis reload karnay kay liay koi option nahi hai.

**Comment by anjumanjum** [comment]
I have Complete this task Plz Retest and Update the status

**Comment by NasirNiazkiyani** [comment]
Fixed...
