### ISSUE TITLE
Menu and homepage view change

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#13]
Home Page

User login pe page blank show karwana hai, user table remove kar do. 

Menus

Accounting or Finance aik hee menu mein karna hai  - Acccounting – Finance ko remove kar kay uss kay sub menus bhi accounting mein daalnay hain. 

Menus ka order yeh karna hai. 

Business Entity
Business Documents
Products
Accounting
Support
Global Documents
System Users
System Data

**Comment by anjumanjum** [comment]
Kindly Re order the Menu

**Comment by NasirNiazkiyani** [comment]
Fixed...
