### ISSUE TITLE
Support & Products Testing So far. 

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#3]
Support Section

Support kay table mein Search option kaam nahi kar rahi hai. Koi bhi ticket search karo lo results mein show nahi hoti aur table blank ho jata hai. Table dubara show karnay kay liay koi solution hona chahiay like a button to show complete results or reload table. 

Support kay table mein jo search bar hai uss ki alignment nahi theek. 

Support kay table mein table headings mein underscore kion aa raha hai ? underscore nahi aana chahia. 

Support tickets kay table mein Full_Title ki jaga Customer Name aana chahiay aur value “Full Title” walay attribute ki aaiy gi, means heading “Customer” aur uss column ki value “Full Title” walay attribute se aaiy gi. 

System Data -> Supp Stat ????? Poora naam Support Status hai… iss kay lookup table kay page mein bhi Page heading k spellings theek karo. 

Services -> Service History -> Service Detail -> Open popup = Iss mein end pe aik } (bracket aa rahi hai iss ko remove karna hai. 

Services -> Service History -> Service Detail Table = Remove the Description and remarks attributes from the table, yeh sirf popup mein hee kafi hain. 

Create New ticket page -> Select Customer drop down = iss mein customer kay FULL TITLE aain gay not contact person name

Support ticket status colors -> Open = Red, Closed = Green. 

Support tickets -> Start Date & End date.. inn sub mein time aik hee aa rha ahai 12:00 AM aur yeh ghalat time day raha hai… ya to iss ko sahi save aur show karwana hai ya iss ko disable kar kay sirf date kar do agar possible nahi to…close date kay time ka bhi yehi masla hai….

Support ticket table mein records ki sorting theek nahi hai,, yeh pehlay bhi bahut baar discuss hua hai, feedback dia hai lekin yeh correct nahi kia…
Deadline Ascending (jo deadline pehlay hai who pehlay aaiy gi) AND
Ticket status = open 
In 2 conditions per table ko sort karna hai, 

Products Section

Products -> View All Products Table = Description ka field table se nikal do, description lambi ho gi to show nahi ho gi. 

Products -> View All products -> edit product page = Page title show nahi ho rahai, show the lable “Product Details”

Product -> View All products = Search is not working, search field ki alignment bhi nahi theek. Blank table se all records view kay liay reload table ka button lagao warna user ko ooper kay menu se dubara aana paray ga.

**Comment by anjumanjum** [comment]
Please do its as soon as possible
