### ISSUE TITLE
Global Documents. 

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#32]
Global documents ka page banana hai. 

![globaldocuments](https://cloud.githubusercontent.com/assets/20052374/16319002/e6681dea-39aa-11e6-9905-6003a3f04e0c.jpg)

**Comment by anjumanjum** [comment]
yar Nasir ye screen b bnaa lo but pehly jo choty se task hn wo kr lo plz.aj aur kl hr trraaa se
