### ISSUE TITLE
Look UP Tables Correction

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#4]
System Data – Look Up Tables

Remove the Delete option from following look up tables please. 

User Roles
User Status
Support Type
Task Type
Support Status
Notes Type
Brands
Business Status
Dispatch Type
Doc Type (Iss ko rename bhi kar do to “Business Document Type”
Rent Status : Yeh Rent Status kaun sa table hai ???? I think yeh Renewal Status hai …
Account Types
Payment Method
Transaction Mode

Ok I am sorry, pehlay delete option daalnay ka kaha tha, plz in mein se delete option nikaal dena.

**Comment by NasirNiazkiyani** [comment]
Fixed...
