### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#5]
Messages -> View All messages

Jub koi message read ho jai to uss ko bold nahi rehna chahiay

**Comment by anjumanjum** [comment]
yar message k table mn isread ka flag h aik jb b sms k detail pe jay to us sms ko update krwoo do just isread true krnaa h baqi wohi model aay ga.plzz fix it

**Comment by NasirNiazkiyani** [comment]
Fixed....
