### ISSUE TITLE
Messages Table

### ISSUE THREAD

**Issue by mwyousaf** [serviceproviderpk/LSM#8]
Jo messages ka table hai uss mein kisis bhi message kay check box per click karein to open ho jata hai... yaa to check box hee hata do ya phir uss ka koi use hona chahiay jaisay koi check box select karay aur oopre se action bhi select karay like delete etc. plz check.

**Comment by anjumanjum** [comment]
Remove the check box plz

**Comment by NasirNiazkiyani** [comment]
Fixed
